### ISSUE TITLE
Reword Labs to reference the array created in Lab 1?

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/ruby-vs-js-arrays#11] opened 2016-06-07 19:43 UTC
Therefore everyone has an array to work with? If so, the questions needs to be changed to match the correct items in the array. 

i.e. Array from Lab 1 would have a length of 8 items, but question 2 and 3 wouldn't work for the array that is created previously.

**Comment by gaand** [comment] 2016-06-07 19:58
``` diff
- Access the 3rd element from the end of an array length of 5.
+ Access the 3rd element from the end of the array for a length of 5.
```

**Comment by gaand** [comment] 2016-06-07 19:59
If I'm understanding your numbering correctly, question 3 does in fact work. 

If it's an appropriate question is a different issue.

**Comment by berziiii** [comment] 2016-06-07 20:05
Correction. I meant questions 3 / 4.

**Comment by neugierige** [comment] 2016-11-01 13:59
Currently, lab 1 does not exist on the master branch. Should I put it back? Also, the potential problem with question 4 seems to be related to issue #9, yes?

**Comment by neugierige** [comment] 2016-11-01 18:04
this is no longer an issue, since lab 1 has been moved to "Bonus"

ok to close?

**Comment by gaand** [comment] 2016-11-02 19:39
I believe this is a duplicate of #9

**Closed as completed by gaand** 2016-11-02 19:39 UTC
Labels: duplicate
